create table address (address_id bigint not null, city varchar(255), created_date datetime not null, door_no varchar(255), layout varchar(255), pin_code varchar(255), street_name varchar(255), updated_date datetime not null, primary key (address_id)) engine=InnoDB;
create table cart_items (id bigint not null auto_increment, created_date datetime not null, quantity integer, updated_date datetime not null, cart_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table carts (cart_id bigint not null auto_increment, created_date datetime not null, updated_date datetime not null, primary key (cart_id)) engine=InnoDB;
create table category (category_id bigint not null auto_increment, description varchar(255), category_name varchar(255), created_date datetime not null, updated_date datetime not null, primary key (category_id)) engine=InnoDB;
create table customer_cart (cart_id bigint not null, customer_id bigint not null, primary key (cart_id, customer_id)) engine=InnoDB;
create table customer_order (customer_id bigint not null, order_id bigint not null, primary key (customer_id, order_id)) engine=InnoDB;
create table customers (customer_id bigint not null auto_increment, created_date datetime not null, email varchar(255), first_name varchar(255), gender varchar(255), last_name varchar(255), mobile varchar(255), password varchar(255), updated_date datetime not null, billing_address_address_id bigint, shipping_address_address_id bigint, primary key (customer_id)) engine=InnoDB;
create table inventory (id bigint not null auto_increment, created_date datetime not null, product_id bigint, quantity integer, updated_date datetime not null, primary key (id)) engine=InnoDB;
create table order (order_id bigint not null auto_increment, created_date datetime not null, updated_date datetime not null, primary key (order_id)) engine=InnoDB;
create table roles (role_id bigint not null auto_increment, access_type varchar(255), role varchar(255), primary key (role_id)) engine=InnoDB;
create table users (user_id bigint not null auto_increment, email varchar(255), password varchar(255), username varchar(255), primary key (user_id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
create table carts_line_items (cart_cart_id bigint not null, line_items_id bigint not null, primary key (cart_cart_id, line_items_id)) engine=InnoDB;
create table customer_roles (customer_id bigint not null, role_id bigint not null) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table order_line_items (order_order_id bigint not null, line_items_id bigint not null, primary key (order_order_id, line_items_id)) engine=InnoDB;
create table products (product_id bigint not null auto_increment, created_date datetime not null, product_description varchar(255), discount_price varchar(255), product_name varchar(255), product_price decimal(19,2), updated_date datetime not null, primary key (product_id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table carts_line_items add constraint UK_2akhxtgqky3djibenwfy9nhmk unique (line_items_id);
alter table order_line_items add constraint UK_d8kybsyv5m3c33ou66lv6mg1m unique (line_items_id);
alter table cart_items add constraint FKpcttvuq4mxppo8sxggjtn5i2c foreign key (cart_id) references carts (cart_id);
alter table cart_items add constraint FK1re40cjegsfvw58xrkdp6bac6 foreign key (product_id) references products (product_id);
alter table customers add constraint FKejbxad5miefgr7wiga9aytwvq foreign key (billing_address_address_id) references address (address_id);
alter table customers add constraint FKfdrd6g0favw9g9x3f8wxcp19a foreign key (shipping_address_address_id) references address (address_id);
alter table carts_line_items add constraint FKnq6vvg53ua5ju1pv1bip8h58s foreign key (line_items_id) references cart_items (id);
alter table carts_line_items add constraint FK8fxvtgs4iwjfu0ghajahig3e0 foreign key (cart_cart_id) references carts (cart_id);
alter table customer_roles add constraint FKnjtvg9npn1etke1ldeffa0ym6 foreign key (role_id) references roles (role_id);
alter table customer_roles add constraint FKgee5mori29s8ae8hwcl23qxf0 foreign key (customer_id) references customers (customer_id);
alter table order_line_items add constraint FKdurt1rmy5mu5jgwhkgy6err3n foreign key (line_items_id) references cart_items (id);
alter table order_line_items add constraint FKccrlfubvjm8cucsta8dqp41os foreign key (order_order_id) references order (order_id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (role_id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (user_id);
