server:
  port: 9091
  servlet:
    context-path: /product
spring:
  application:
    name: PRODUCT-API
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/ShoppingServer/eureka/}
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "health, info"

