eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
  servlet:
    context-path: /ShoppingServer
management:
  endpoints:
    web:
      exposure:
        include: "health, info"